name: issue-to-project-board-workflow
on:
  issues:
    types: [reopened, closed, labeled, unlabeled, assigned, unassigned]

jobs:
  manage_project_issues:
    strategy:
      fail-fast: false
      matrix:
        project: 
          - 'TestBoard'
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'good first issue')
    steps:
      - name: Create or Update Project Card
        if: | 
          github.event.action == 'labeled' || 
          github.event.action == 'reopened' || 
          github.event.action == 'unassigned'
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ${{ matrix.project }}
          column: 'Todo'
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_PAT }}

        # When an issue that is open is assigned and has an assigned member
        # create or move the card to "In progress"
      - name: Assign Project Card
        if: |
          github.event.action == 'assigned' 
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ${{ matrix.project }}
          column: 'In Progress'
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_PAT }}
        # When an issue is closed with the good first issue tag
        # Create or move the card to "Done"
      - name: Close Project Card
        if: |
          github.event.action == 'closed'
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ${{ matrix.project }}
          column: 'Done'
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_PAT }}
  remove_project_issues:
    strategy:
      fail-fast: false
      matrix:
        project:
          - 'Test Board GA'
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.issue.labels.*.name, 'good first issue') }}
    steps:
        # When an issue has the tag 'good first issue' removed
        # Remove the card from the board
      - name: Remove Project Card
        if: |
          github.event.action == 'unlabeled'
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ${{ matrix.project }}
          column: 'Todo'
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_PAT }}
          action: delete
